# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Remote(object):
    def setupUi(self, Remote):
        Remote.setObjectName("Remote")
        Remote.resize(450, 450)
        Remote.setMinimumSize(QtCore.QSize(450, 450))
        Remote.setMaximumSize(QtCore.QSize(450, 450))
        self.centralwidget = QtWidgets.QWidget(parent=Remote)
        self.centralwidget.setObjectName("centralwidget")
        self.remote = QtWidgets.QFrame(parent=self.centralwidget)
        self.remote.setGeometry(QtCore.QRect(30, 30, 200, 350))
        self.remote.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.remote.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.remote.setObjectName("remote")
        self.power_button = QtWidgets.QPushButton(parent=self.remote)
        self.power_button.setGeometry(QtCore.QRect(20, 20, 50, 30))
        self.power_button.setObjectName("power_button")
        self.mute_button = QtWidgets.QPushButton(parent=self.remote)
        self.mute_button.setGeometry(QtCore.QRect(130, 20, 50, 30))
        self.mute_button.setObjectName("mute_button")
        self.volume_up = QtWidgets.QPushButton(parent=self.remote)
        self.volume_up.setGeometry(QtCore.QRect(20, 150, 51, 31))
        self.volume_up.setObjectName("volume_up")
        self.channel_up = QtWidgets.QPushButton(parent=self.remote)
        self.channel_up.setGeometry(QtCore.QRect(110, 150, 51, 31))
        self.channel_up.setObjectName("channel_up")
        self.volume_down = QtWidgets.QPushButton(parent=self.remote)
        self.volume_down.setGeometry(QtCore.QRect(20, 220, 51, 28))
        self.volume_down.setObjectName("volume_down")
        self.channel_down = QtWidgets.QPushButton(parent=self.remote)
        self.channel_down.setGeometry(QtCore.QRect(110, 220, 51, 28))
        self.channel_down.setObjectName("channel_down")
        self.volume_label = QtWidgets.QLabel(parent=self.remote)
        self.volume_label.setGeometry(QtCore.QRect(20, 180, 51, 41))
        self.volume_label.setObjectName("volume_label")
        self.channel_label = QtWidgets.QLabel(parent=self.remote)
        self.channel_label.setGeometry(QtCore.QRect(110, 180, 51, 41))
        self.channel_label.setObjectName("channel_label")
        self.status = QtWidgets.QLabel(parent=self.centralwidget)
        self.status.setGeometry(QtCore.QRect(260, 30, 161, 20))
        self.status.setObjectName("status")
        self.power_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.power_status.setGeometry(QtCore.QRect(260, 70, 151, 16))
        self.power_status.setObjectName("power_status")
        self.volume_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.volume_status.setGeometry(QtCore.QRect(260, 110, 151, 16))
        self.volume_status.setObjectName("volume_status")
        self.channel_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_status.setGeometry(QtCore.QRect(260, 150, 151, 16))
        self.channel_status.setObjectName("channel_status")
        Remote.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Remote)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        Remote.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Remote)
        self.statusbar.setObjectName("statusbar")
        Remote.setStatusBar(self.statusbar)

        self.retranslateUi(Remote)
        QtCore.QMetaObject.connectSlotsByName(Remote)

    def retranslateUi(self, Remote):
        _translate = QtCore.QCoreApplication.translate
        Remote.setWindowTitle(_translate("Remote", "Television"))
        self.power_button.setText(_translate("Remote", "Power"))
        self.mute_button.setText(_translate("Remote", "Mute"))
        self.volume_up.setText(_translate("Remote", "UP"))
        self.channel_up.setText(_translate("Remote", "UP"))
        self.volume_down.setText(_translate("Remote", "DOWN"))
        self.channel_down.setText(_translate("Remote", "DOWN"))
        self.volume_label.setText(_translate("Remote", "Volume"))
        self.channel_label.setText(_translate("Remote", "Channel"))
        self.status.setText(_translate("Remote", "Current Television Status:"))
        self.power_status.setText(_translate("Remote", "Power: OFF"))
        self.volume_status.setText(_translate("Remote", "Volume: 0"))
        self.channel_status.setText(_translate("Remote", "Channel: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Remote = QtWidgets.QMainWindow()
    ui = Ui_Remote()
    ui.setupUi(Remote)
    Remote.show()
    sys.exit(app.exec())
