# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 450)
        MainWindow.setMinimumSize(QtCore.QSize(450, 450))
        MainWindow.setMaximumSize(QtCore.QSize(450, 450))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.remote = QtWidgets.QFrame(parent=self.centralwidget)
        self.remote.setGeometry(QtCore.QRect(30, 30, 200, 350))
        self.remote.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.remote.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.remote.setObjectName("remote")
        self.power_button = QtWidgets.QPushButton(parent=self.remote)
        self.power_button.setGeometry(QtCore.QRect(20, 20, 50, 30))
        self.power_button.setObjectName("power_button")
        self.mute_button = QtWidgets.QPushButton(parent=self.remote)
        self.mute_button.setGeometry(QtCore.QRect(130, 20, 50, 30))
        self.mute_button.setObjectName("mute_button")
        self.pushButton = QtWidgets.QPushButton(parent=self.remote)
        self.pushButton.setGeometry(QtCore.QRect(20, 150, 51, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.remote)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 150, 51, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.remote)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 220, 51, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.remote)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 220, 51, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(parent=self.remote)
        self.label.setGeometry(QtCore.QRect(20, 180, 51, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.remote)
        self.label_2.setGeometry(QtCore.QRect(110, 180, 51, 41))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 30, 171, 350))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Television"))
        self.power_button.setText(_translate("MainWindow", "Power"))
        self.mute_button.setText(_translate("MainWindow", "Mute"))
        self.pushButton.setText(_translate("MainWindow", "UP"))
        self.pushButton_2.setText(_translate("MainWindow", "UP"))
        self.pushButton_3.setText(_translate("MainWindow", "DOWN"))
        self.pushButton_4.setText(_translate("MainWindow", "DOWN"))
        self.label.setText(_translate("MainWindow", "Volume"))
        self.label_2.setText(_translate("MainWindow", "Channel"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Current Status:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Power: OFF</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Volume: 0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Channel: 0</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
